/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteEducationHistoryArgs } from "./DeleteEducationHistoryArgs";
import { EducationHistoryFindManyArgs } from "./EducationHistoryFindManyArgs";
import { EducationHistoryFindUniqueArgs } from "./EducationHistoryFindUniqueArgs";
import { EducationHistory } from "./EducationHistory";
import { EducationHistoryService } from "../educationHistory.service";

@graphql.Resolver(() => EducationHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EducationHistoryResolverBase {
  constructor(
    protected readonly service: EducationHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EducationHistory",
    action: "read",
    possession: "any",
  })
  async _educationHistoriesMeta(
    @graphql.Args() args: EducationHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [EducationHistory])
  @nestAccessControl.UseRoles({
    resource: "EducationHistory",
    action: "read",
    possession: "any",
  })
  async educationHistories(
    @graphql.Args() args: EducationHistoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EducationHistory[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "EducationHistory",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => EducationHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EducationHistory",
    action: "read",
    possession: "own",
  })
  async educationHistory(
    @graphql.Args() args: EducationHistoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<EducationHistory | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "EducationHistory",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => EducationHistory)
  @nestAccessControl.UseRoles({
    resource: "EducationHistory",
    action: "delete",
    possession: "any",
  })
  async deleteEducationHistory(
    @graphql.Args() args: DeleteEducationHistoryArgs
  ): Promise<EducationHistory | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
