/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TravelHistoryService } from "../travelHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TravelHistoryCreateInput } from "./TravelHistoryCreateInput";
import { TravelHistoryWhereInput } from "./TravelHistoryWhereInput";
import { TravelHistoryWhereUniqueInput } from "./TravelHistoryWhereUniqueInput";
import { TravelHistoryFindManyArgs } from "./TravelHistoryFindManyArgs";
import { TravelHistoryUpdateInput } from "./TravelHistoryUpdateInput";
import { TravelHistory } from "./TravelHistory";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TravelHistoryControllerBase {
  constructor(
    protected readonly service: TravelHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TravelHistory })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: TravelHistoryCreateInput
  ): Promise<TravelHistory> {
    return await this.service.create({
      data: {
        ...data,

        applicant: data.applicant
          ? {
              connect: data.applicant,
            }
          : undefined,

        archivedBy: data.archivedBy
          ? {
              connect: data.archivedBy,
            }
          : undefined,

        createdBy: data.createdBy
          ? {
              connect: data.createdBy,
            }
          : undefined,

        updatedBy: data.updatedBy
          ? {
              connect: data.updatedBy,
            }
          : undefined,
      },
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateDeparted: true,
        dateEntered: true,
        destinationCity: true,
        destinationCountry: true,
        destinationHub: true,
        id: true,
        reasonOfTravel: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [TravelHistory] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TravelHistoryFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<TravelHistory[]> {
    const args = plainToClass(TravelHistoryFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateDeparted: true,
        dateEntered: true,
        destinationCity: true,
        destinationCountry: true,
        destinationHub: true,
        id: true,
        reasonOfTravel: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TravelHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TravelHistoryWhereUniqueInput
  ): Promise<TravelHistory | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateDeparted: true,
        dateEntered: true,
        destinationCity: true,
        destinationCountry: true,
        destinationHub: true,
        id: true,
        reasonOfTravel: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TravelHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TravelHistoryWhereUniqueInput,
    @common.Body() data: TravelHistoryUpdateInput
  ): Promise<TravelHistory | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          applicant: data.applicant
            ? {
                connect: data.applicant,
              }
            : undefined,

          archivedBy: data.archivedBy
            ? {
                connect: data.archivedBy,
              }
            : undefined,

          createdBy: data.createdBy
            ? {
                connect: data.createdBy,
              }
            : undefined,

          updatedBy: data.updatedBy
            ? {
                connect: data.updatedBy,
              }
            : undefined,
        },
        select: {
          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          dateDeparted: true,
          dateEntered: true,
          destinationCity: true,
          destinationCountry: true,
          destinationHub: true,
          id: true,
          reasonOfTravel: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TravelHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TravelHistoryWhereUniqueInput
  ): Promise<TravelHistory | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          dateDeparted: true,
          dateEntered: true,
          destinationCity: true,
          destinationCountry: true,
          destinationHub: true,
          id: true,
          reasonOfTravel: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
