/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTravelHistoryArgs } from "./CreateTravelHistoryArgs";
import { UpdateTravelHistoryArgs } from "./UpdateTravelHistoryArgs";
import { DeleteTravelHistoryArgs } from "./DeleteTravelHistoryArgs";
import { TravelHistoryFindManyArgs } from "./TravelHistoryFindManyArgs";
import { TravelHistoryFindUniqueArgs } from "./TravelHistoryFindUniqueArgs";
import { TravelHistory } from "./TravelHistory";
import { Applicant } from "../../applicant/base/Applicant";
import { User } from "../../user/base/User";
import { TravelHistoryService } from "../travelHistory.service";

@graphql.Resolver(() => TravelHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TravelHistoryResolverBase {
  constructor(
    protected readonly service: TravelHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "read",
    possession: "any",
  })
  async _travelHistoriesMeta(
    @graphql.Args() args: TravelHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TravelHistory])
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "read",
    possession: "any",
  })
  async travelHistories(
    @graphql.Args() args: TravelHistoryFindManyArgs
  ): Promise<TravelHistory[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TravelHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "read",
    possession: "own",
  })
  async travelHistory(
    @graphql.Args() args: TravelHistoryFindUniqueArgs
  ): Promise<TravelHistory | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TravelHistory)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "create",
    possession: "any",
  })
  async createTravelHistory(
    @graphql.Args() args: CreateTravelHistoryArgs
  ): Promise<TravelHistory> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        applicant: args.data.applicant
          ? {
              connect: args.data.applicant,
            }
          : undefined,

        archivedBy: args.data.archivedBy
          ? {
              connect: args.data.archivedBy,
            }
          : undefined,

        createdBy: args.data.createdBy
          ? {
              connect: args.data.createdBy,
            }
          : undefined,

        updatedBy: args.data.updatedBy
          ? {
              connect: args.data.updatedBy,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TravelHistory)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "update",
    possession: "any",
  })
  async updateTravelHistory(
    @graphql.Args() args: UpdateTravelHistoryArgs
  ): Promise<TravelHistory | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          applicant: args.data.applicant
            ? {
                connect: args.data.applicant,
              }
            : undefined,

          archivedBy: args.data.archivedBy
            ? {
                connect: args.data.archivedBy,
              }
            : undefined,

          createdBy: args.data.createdBy
            ? {
                connect: args.data.createdBy,
              }
            : undefined,

          updatedBy: args.data.updatedBy
            ? {
                connect: args.data.updatedBy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TravelHistory)
  @nestAccessControl.UseRoles({
    resource: "TravelHistory",
    action: "delete",
    possession: "any",
  })
  async deleteTravelHistory(
    @graphql.Args() args: DeleteTravelHistoryArgs
  ): Promise<TravelHistory | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Applicant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Applicant",
    action: "read",
    possession: "any",
  })
  async applicant(
    @graphql.Parent() parent: TravelHistory
  ): Promise<Applicant | null> {
    const result = await this.service.getApplicant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async archivedBy(
    @graphql.Parent() parent: TravelHistory
  ): Promise<User | null> {
    const result = await this.service.getArchivedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async createdBy(
    @graphql.Parent() parent: TravelHistory
  ): Promise<User | null> {
    const result = await this.service.getCreatedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async updatedBy(
    @graphql.Parent() parent: TravelHistory
  ): Promise<User | null> {
    const result = await this.service.getUpdatedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
