/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, TravelHistory, Applicant, User } from "@prisma/client";

export class TravelHistoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.TravelHistoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryFindManyArgs>
  ): Promise<number> {
    return this.prisma.travelHistory.count(args);
  }

  async findMany<T extends Prisma.TravelHistoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryFindManyArgs>
  ): Promise<TravelHistory[]> {
    return this.prisma.travelHistory.findMany(args);
  }
  async findOne<T extends Prisma.TravelHistoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryFindUniqueArgs>
  ): Promise<TravelHistory | null> {
    return this.prisma.travelHistory.findUnique(args);
  }
  async create<T extends Prisma.TravelHistoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryCreateArgs>
  ): Promise<TravelHistory> {
    return this.prisma.travelHistory.create<T>(args);
  }
  async update<T extends Prisma.TravelHistoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryUpdateArgs>
  ): Promise<TravelHistory> {
    return this.prisma.travelHistory.update<T>(args);
  }
  async delete<T extends Prisma.TravelHistoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TravelHistoryDeleteArgs>
  ): Promise<TravelHistory> {
    return this.prisma.travelHistory.delete(args);
  }

  async getApplicant(parentId: string): Promise<Applicant | null> {
    return this.prisma.travelHistory
      .findUnique({
        where: { id: parentId },
      })
      .applicant();
  }

  async getArchivedBy(parentId: string): Promise<User | null> {
    return this.prisma.travelHistory
      .findUnique({
        where: { id: parentId },
      })
      .archivedBy();
  }

  async getCreatedBy(parentId: string): Promise<User | null> {
    return this.prisma.travelHistory
      .findUnique({
        where: { id: parentId },
      })
      .createdBy();
  }

  async getUpdatedBy(parentId: string): Promise<User | null> {
    return this.prisma.travelHistory
      .findUnique({
        where: { id: parentId },
      })
      .updatedBy();
  }
}
