import { Applicant } from "../applicant/Applicant";
import { EducationHistory } from "../educationHistory/EducationHistory";
import { EmploymentHistory } from "../employmentHistory/EmploymentHistory";
import { FamilyMember } from "../familyMember/FamilyMember";
import { PersonalInfo } from "../personalInfo/PersonalInfo";
import { TravelHistory } from "../travelHistory/TravelHistory";

export type User = {
  applicants?: Array<Applicant>;
  applicantsArchived?: Array<Applicant>;
  applicantsCreated?: Array<Applicant>;
  applicantsUpdated?: Array<Applicant>;
  createdAt: Date;
  educationHistoriesArchived?: Array<EducationHistory>;
  educationHistoriesCreated?: Array<EducationHistory>;
  educationHistoriesUpdated?: Array<EducationHistory>;
  email: string | null;
  employmentHistoriesArchived?: Array<EmploymentHistory>;
  employmentHistoriesCreated?: Array<EmploymentHistory>;
  employmentHistoriesUpdated?: Array<EmploymentHistory>;
  familyMembersArchived?: Array<FamilyMember>;
  familyMembersCreated?: Array<FamilyMember>;
  familyMembersUpdated?: Array<FamilyMember>;
  firstName: string | null;
  id: string;
  lastName: string | null;
  personalInfosArchived?: Array<PersonalInfo>;
  personalInfosCreated?: Array<PersonalInfo>;
  personalInfosUpdated?: Array<PersonalInfo>;
  roles: Array<string>;
  travelHistoriesArchived?: Array<TravelHistory>;
  travelHistoriesCreated?: Array<TravelHistory>;
  travelHistoriesUpdated?: Array<TravelHistory>;
  updatedAt: Date;
  username: string;
};
