/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  Applicant,
  EducationHistory,
  EmploymentHistory,
  FamilyMember,
  TravelHistory,
  User,
  PersonalInfo,
} from "@prisma/client";

export class ApplicantServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ApplicantFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantFindManyArgs>
  ): Promise<number> {
    return this.prisma.applicant.count(args);
  }

  async findMany<T extends Prisma.ApplicantFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantFindManyArgs>
  ): Promise<Applicant[]> {
    return this.prisma.applicant.findMany(args);
  }
  async findOne<T extends Prisma.ApplicantFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantFindUniqueArgs>
  ): Promise<Applicant | null> {
    return this.prisma.applicant.findUnique(args);
  }
  async create<T extends Prisma.ApplicantCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantCreateArgs>
  ): Promise<Applicant> {
    return this.prisma.applicant.create<T>(args);
  }
  async update<T extends Prisma.ApplicantUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantUpdateArgs>
  ): Promise<Applicant> {
    return this.prisma.applicant.update<T>(args);
  }
  async delete<T extends Prisma.ApplicantDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicantDeleteArgs>
  ): Promise<Applicant> {
    return this.prisma.applicant.delete(args);
  }

  async findEducationHistories(
    parentId: string,
    args: Prisma.EducationHistoryFindManyArgs
  ): Promise<EducationHistory[]> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .educationHistories(args);
  }

  async findEmploymentHistories(
    parentId: string,
    args: Prisma.EmploymentHistoryFindManyArgs
  ): Promise<EmploymentHistory[]> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .employmentHistories(args);
  }

  async findFamilyMembers(
    parentId: string,
    args: Prisma.FamilyMemberFindManyArgs
  ): Promise<FamilyMember[]> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .familyMembers(args);
  }

  async findTravelHistories(
    parentId: string,
    args: Prisma.TravelHistoryFindManyArgs
  ): Promise<TravelHistory[]> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .travelHistories(args);
  }

  async findUpdatedBy(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<User[]> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .updatedBy(args);
  }

  async getArchivedBy(parentId: string): Promise<User | null> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .archivedBy();
  }

  async getCreatedBy(parentId: string): Promise<User | null> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .createdBy();
  }

  async getPersonalInfo(parentId: string): Promise<PersonalInfo | null> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .personalInfo();
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.applicant
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
