/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePersonalInfoArgs } from "./CreatePersonalInfoArgs";
import { UpdatePersonalInfoArgs } from "./UpdatePersonalInfoArgs";
import { DeletePersonalInfoArgs } from "./DeletePersonalInfoArgs";
import { PersonalInfoFindManyArgs } from "./PersonalInfoFindManyArgs";
import { PersonalInfoFindUniqueArgs } from "./PersonalInfoFindUniqueArgs";
import { PersonalInfo } from "./PersonalInfo";
import { Applicant } from "../../applicant/base/Applicant";
import { User } from "../../user/base/User";
import { PersonalInfoService } from "../personalInfo.service";

@graphql.Resolver(() => PersonalInfo)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PersonalInfoResolverBase {
  constructor(
    protected readonly service: PersonalInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async _personalInfosMeta(
    @graphql.Args() args: PersonalInfoFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [PersonalInfo])
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async personalInfos(
    @graphql.Args() args: PersonalInfoFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PersonalInfo[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PersonalInfo",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => PersonalInfo, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "own",
  })
  async personalInfo(
    @graphql.Args() args: PersonalInfoFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PersonalInfo | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PersonalInfo",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => PersonalInfo)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "create",
    possession: "any",
  })
  async createPersonalInfo(
    @graphql.Args() args: CreatePersonalInfoArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PersonalInfo> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PersonalInfo",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PersonalInfo"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        applicant: args.data.applicant
          ? {
              connect: args.data.applicant,
            }
          : undefined,

        archivedBy: args.data.archivedBy
          ? {
              connect: args.data.archivedBy,
            }
          : undefined,

        createdBy: args.data.createdBy
          ? {
              connect: args.data.createdBy,
            }
          : undefined,

        updatedBy: args.data.updatedBy
          ? {
              connect: args.data.updatedBy,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PersonalInfo)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "update",
    possession: "any",
  })
  async updatePersonalInfo(
    @graphql.Args() args: UpdatePersonalInfoArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PersonalInfo | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PersonalInfo",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PersonalInfo"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          applicant: args.data.applicant
            ? {
                connect: args.data.applicant,
              }
            : undefined,

          archivedBy: args.data.archivedBy
            ? {
                connect: args.data.archivedBy,
              }
            : undefined,

          createdBy: args.data.createdBy
            ? {
                connect: args.data.createdBy,
              }
            : undefined,

          updatedBy: args.data.updatedBy
            ? {
                connect: args.data.updatedBy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PersonalInfo)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "delete",
    possession: "any",
  })
  async deletePersonalInfo(
    @graphql.Args() args: DeletePersonalInfoArgs
  ): Promise<PersonalInfo | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Applicant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async applicant(
    @graphql.Parent() parent: PersonalInfo,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Applicant | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Applicant",
    });
    const result = await this.service.getApplicant(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async archivedBy(
    @graphql.Parent() parent: PersonalInfo,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getArchivedBy(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async createdBy(
    @graphql.Parent() parent: PersonalInfo,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getCreatedBy(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  async updatedBy(
    @graphql.Parent() parent: PersonalInfo,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUpdatedBy(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
