/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PersonalInfoService } from "../personalInfo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalInfoCreateInput } from "./PersonalInfoCreateInput";
import { PersonalInfoWhereInput } from "./PersonalInfoWhereInput";
import { PersonalInfoWhereUniqueInput } from "./PersonalInfoWhereUniqueInput";
import { PersonalInfoFindManyArgs } from "./PersonalInfoFindManyArgs";
import { PersonalInfoUpdateInput } from "./PersonalInfoUpdateInput";
import { PersonalInfo } from "./PersonalInfo";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PersonalInfoControllerBase {
  constructor(
    protected readonly service: PersonalInfoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalInfo })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PersonalInfoCreateInput
  ): Promise<PersonalInfo> {
    return await this.service.create({
      data: {
        ...data,

        applicant: data.applicant
          ? {
              connect: data.applicant,
            }
          : undefined,

        archivedBy: data.archivedBy
          ? {
              connect: data.archivedBy,
            }
          : undefined,

        createdBy: data.createdBy
          ? {
              connect: data.createdBy,
            }
          : undefined,

        updatedBy: data.updatedBy
          ? {
              connect: data.updatedBy,
            }
          : undefined,
      },
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        countriesOfCitizenship: true,
        countryOfBirth: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateOfBirth: true,
        email: true,
        firstName: true,
        homeCountryAddress: true,
        id: true,
        inzClientNumber: true,
        lastName: true,
        mobile: true,
        nzAddress: true,
        passportNumber: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalInfo] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PersonalInfoFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PersonalInfo[]> {
    const args = plainToClass(PersonalInfoFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        countriesOfCitizenship: true,
        countryOfBirth: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateOfBirth: true,
        email: true,
        firstName: true,
        homeCountryAddress: true,
        id: true,
        inzClientNumber: true,
        lastName: true,
        mobile: true,
        nzAddress: true,
        passportNumber: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PersonalInfoWhereUniqueInput
  ): Promise<PersonalInfo | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        countriesOfCitizenship: true,
        countryOfBirth: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        dateOfBirth: true,
        email: true,
        firstName: true,
        homeCountryAddress: true,
        id: true,
        inzClientNumber: true,
        lastName: true,
        mobile: true,
        nzAddress: true,
        passportNumber: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PersonalInfoWhereUniqueInput,
    @common.Body() data: PersonalInfoUpdateInput
  ): Promise<PersonalInfo | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          applicant: data.applicant
            ? {
                connect: data.applicant,
              }
            : undefined,

          archivedBy: data.archivedBy
            ? {
                connect: data.archivedBy,
              }
            : undefined,

          createdBy: data.createdBy
            ? {
                connect: data.createdBy,
              }
            : undefined,

          updatedBy: data.updatedBy
            ? {
                connect: data.updatedBy,
              }
            : undefined,
        },
        select: {
          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          countriesOfCitizenship: true,
          countryOfBirth: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          dateOfBirth: true,
          email: true,
          firstName: true,
          homeCountryAddress: true,
          id: true,
          inzClientNumber: true,
          lastName: true,
          mobile: true,
          nzAddress: true,
          passportNumber: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PersonalInfo",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PersonalInfoWhereUniqueInput
  ): Promise<PersonalInfo | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          countriesOfCitizenship: true,
          countryOfBirth: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          dateOfBirth: true,
          email: true,
          firstName: true,
          homeCountryAddress: true,
          id: true,
          inzClientNumber: true,
          lastName: true,
          mobile: true,
          nzAddress: true,
          passportNumber: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
