/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EmploymentHistoryService } from "../employmentHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmploymentHistoryCreateInput } from "./EmploymentHistoryCreateInput";
import { EmploymentHistoryWhereInput } from "./EmploymentHistoryWhereInput";
import { EmploymentHistoryWhereUniqueInput } from "./EmploymentHistoryWhereUniqueInput";
import { EmploymentHistoryFindManyArgs } from "./EmploymentHistoryFindManyArgs";
import { EmploymentHistoryUpdateInput } from "./EmploymentHistoryUpdateInput";
import { EmploymentHistory } from "./EmploymentHistory";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmploymentHistoryControllerBase {
  constructor(
    protected readonly service: EmploymentHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmploymentHistory })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: EmploymentHistoryCreateInput
  ): Promise<EmploymentHistory> {
    return await this.service.create({
      data: {
        ...data,

        applicant: data.applicant
          ? {
              connect: data.applicant,
            }
          : undefined,

        archivedBy: data.archivedBy
          ? {
              connect: data.archivedBy,
            }
          : undefined,

        createdBy: data.createdBy
          ? {
              connect: data.createdBy,
            }
          : undefined,

        updatedBy: data.updatedBy
          ? {
              connect: data.updatedBy,
            }
          : undefined,
      },
      select: {
        additionalInfo: true,

        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        cityOfWork: true,
        companyName: true,
        countryOfWork: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        duties: true,
        employmentType: true,
        endDate: true,
        id: true,
        isCurrentJob: true,
        jobTitle: true,
        nzBusinessNumber: true,
        startDate: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmploymentHistory] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(EmploymentHistoryFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<EmploymentHistory[]> {
    const args = plainToClass(EmploymentHistoryFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        additionalInfo: true,

        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        cityOfWork: true,
        companyName: true,
        countryOfWork: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        duties: true,
        employmentType: true,
        endDate: true,
        id: true,
        isCurrentJob: true,
        jobTitle: true,
        nzBusinessNumber: true,
        startDate: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmploymentHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: EmploymentHistoryWhereUniqueInput
  ): Promise<EmploymentHistory | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        additionalInfo: true,

        applicant: {
          select: {
            id: true,
          },
        },

        archived: true,

        archivedBy: {
          select: {
            id: true,
          },
        },

        cityOfWork: true,
        companyName: true,
        countryOfWork: true,
        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        duties: true,
        employmentType: true,
        endDate: true,
        id: true,
        isCurrentJob: true,
        jobTitle: true,
        nzBusinessNumber: true,
        startDate: true,
        updatedAt: true,

        updatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmploymentHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: EmploymentHistoryWhereUniqueInput,
    @common.Body() data: EmploymentHistoryUpdateInput
  ): Promise<EmploymentHistory | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          applicant: data.applicant
            ? {
                connect: data.applicant,
              }
            : undefined,

          archivedBy: data.archivedBy
            ? {
                connect: data.archivedBy,
              }
            : undefined,

          createdBy: data.createdBy
            ? {
                connect: data.createdBy,
              }
            : undefined,

          updatedBy: data.updatedBy
            ? {
                connect: data.updatedBy,
              }
            : undefined,
        },
        select: {
          additionalInfo: true,

          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          cityOfWork: true,
          companyName: true,
          countryOfWork: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          duties: true,
          employmentType: true,
          endDate: true,
          id: true,
          isCurrentJob: true,
          jobTitle: true,
          nzBusinessNumber: true,
          startDate: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmploymentHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: EmploymentHistoryWhereUniqueInput
  ): Promise<EmploymentHistory | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          additionalInfo: true,

          applicant: {
            select: {
              id: true,
            },
          },

          archived: true,

          archivedBy: {
            select: {
              id: true,
            },
          },

          cityOfWork: true,
          companyName: true,
          countryOfWork: true,
          createdAt: true,

          createdBy: {
            select: {
              id: true,
            },
          },

          duties: true,
          employmentType: true,
          endDate: true,
          id: true,
          isCurrentJob: true,
          jobTitle: true,
          nzBusinessNumber: true,
          startDate: true,
          updatedAt: true,

          updatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
