/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateEmploymentHistoryArgs } from "./CreateEmploymentHistoryArgs";
import { UpdateEmploymentHistoryArgs } from "./UpdateEmploymentHistoryArgs";
import { DeleteEmploymentHistoryArgs } from "./DeleteEmploymentHistoryArgs";
import { EmploymentHistoryFindManyArgs } from "./EmploymentHistoryFindManyArgs";
import { EmploymentHistoryFindUniqueArgs } from "./EmploymentHistoryFindUniqueArgs";
import { EmploymentHistory } from "./EmploymentHistory";
import { Applicant } from "../../applicant/base/Applicant";
import { User } from "../../user/base/User";
import { EmploymentHistoryService } from "../employmentHistory.service";

@graphql.Resolver(() => EmploymentHistory)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class EmploymentHistoryResolverBase {
  constructor(
    protected readonly service: EmploymentHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "read",
    possession: "any",
  })
  async _employmentHistoriesMeta(
    @graphql.Args() args: EmploymentHistoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EmploymentHistory])
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "read",
    possession: "any",
  })
  async employmentHistories(
    @graphql.Args() args: EmploymentHistoryFindManyArgs
  ): Promise<EmploymentHistory[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EmploymentHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "read",
    possession: "own",
  })
  async employmentHistory(
    @graphql.Args() args: EmploymentHistoryFindUniqueArgs
  ): Promise<EmploymentHistory | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EmploymentHistory)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "create",
    possession: "any",
  })
  async createEmploymentHistory(
    @graphql.Args() args: CreateEmploymentHistoryArgs
  ): Promise<EmploymentHistory> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        applicant: args.data.applicant
          ? {
              connect: args.data.applicant,
            }
          : undefined,

        archivedBy: args.data.archivedBy
          ? {
              connect: args.data.archivedBy,
            }
          : undefined,

        createdBy: args.data.createdBy
          ? {
              connect: args.data.createdBy,
            }
          : undefined,

        updatedBy: args.data.updatedBy
          ? {
              connect: args.data.updatedBy,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EmploymentHistory)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "update",
    possession: "any",
  })
  async updateEmploymentHistory(
    @graphql.Args() args: UpdateEmploymentHistoryArgs
  ): Promise<EmploymentHistory | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          applicant: args.data.applicant
            ? {
                connect: args.data.applicant,
              }
            : undefined,

          archivedBy: args.data.archivedBy
            ? {
                connect: args.data.archivedBy,
              }
            : undefined,

          createdBy: args.data.createdBy
            ? {
                connect: args.data.createdBy,
              }
            : undefined,

          updatedBy: args.data.updatedBy
            ? {
                connect: args.data.updatedBy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EmploymentHistory)
  @nestAccessControl.UseRoles({
    resource: "EmploymentHistory",
    action: "delete",
    possession: "any",
  })
  async deleteEmploymentHistory(
    @graphql.Args() args: DeleteEmploymentHistoryArgs
  ): Promise<EmploymentHistory | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Applicant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Applicant",
    action: "read",
    possession: "any",
  })
  async applicant(
    @graphql.Parent() parent: EmploymentHistory
  ): Promise<Applicant | null> {
    const result = await this.service.getApplicant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async archivedBy(
    @graphql.Parent() parent: EmploymentHistory
  ): Promise<User | null> {
    const result = await this.service.getArchivedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async createdBy(
    @graphql.Parent() parent: EmploymentHistory
  ): Promise<User | null> {
    const result = await this.service.getCreatedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async updatedBy(
    @graphql.Parent() parent: EmploymentHistory
  ): Promise<User | null> {
    const result = await this.service.getUpdatedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
